#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd $(dirname "$0")/..

if type -p java; then
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    _java="$JAVA_HOME/bin/java"
else
    echo "Java needs to be installed"
    exit 1
fi

if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    if [[ "$version" < "1.7" ]]; then
        echo "Java needs to be upgraded to atleast 1.7"
        exit 1
    fi
fi



echo "==> Installing npm dependencies…"
npm install --silent

if ! hash kong 2>/dev/null; then
    echo "==> Install kong"
    brew tap mashape/kong
    brew install kong --with-cassandra
fi
