#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

echo "==> Starting cassandra"
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.cassandra.plist
echo "==> Starting kong"
kong start -c ./kong.yml

echo "==> Applying kong config"
kongfig --path ./config.json --host localhost:8001

echo "==> Kong is ready! To stop kong, run `kong stop`"
